### ISSUE TITLE
[Bug] Velocity modern forwarding setting cannot join limbo

### ISSUE THREAD

**Issue by Yurinann** [Nan1t/NanoLimbo#83]
same as title, my settings:
```
# Player info forwarding support.
# Available types:
#  - NONE
#  - LEGACY
#  - MODERN
#  - BUNGEE_GUARD
# Don't use secret if you do not use MODERN type
infoForwarding:
  type: MODERN
  secret: 'xxxxxxxxxx'
  tokens:
    - '<BUNGEE_GUARD_TOKEN>'
```

Velocity version: 3.3.0-SNAPSHOT-389
NanoLimbo version: 1.8
